import styled from "@emotion/styled";

const DepartedFlightComponentStyles = {
  Container: styled("div")(({ theme }) => ({
    width: "100%",
    display: "flex",
    flexDirection: "column",
    cursor: "pointer",
  })),
  TopDiv: styled("div")(({ theme }) => ({
    border: "0.581px solid #0A1313",
    backgroundColor: "#152E44",
    width: "100%",
    height: "5em",
    display: "flex",
    flexDirection: "row",
  })),
  CarrierLogoDiv: styled("div")(({ theme }) => ({
    paddingTop: "1.5rem",
    paddingBottom: "1.5rem",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRight: "0.581px solid #0A1313",
    width: "20%",
  })),
  FlightDetailsDiv: styled("div")(({ theme }) => ({
    paddingTop: "1rem",
    paddingBottom: "1rem",
    width: "80%",
    display: "flex",
    flexDirection: "row",
    padding: "0 0.7rem",
  })),
  ArrivalDiv: styled("div")(({ theme }) => ({
    width: "40%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  })),
  ArrivalCodeDiv: styled("div")(({ theme }) => ({
    color: "#D6D6D6",
    fontSize: "0.92619rem",
    fontWeight: "500",
  })),
  ArrivedFromDiv: styled("div")(({ theme }) => ({
    color: "rgba(214, 214, 214, 0.6)",
    fontSize: "0.69463rem",
    fontWeight: "500",
    display: "flex",
    justifyContent: "flex-start",
    gap: "0.3rem",
    alignItems: "center",
  })),

  FromAndToLinkDiv: styled("div")(({ theme }) => ({
    color: "#D6D6D6",
    width: "20%",
    fontSize: "0.5rem",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  })),

  DepartureDiv: styled("div")(({ theme }) => ({
    width: "40%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  })),
  DepartureCodeDiv: styled("div")(({ theme }) => ({
    color: "#D6D6D6",
    fontSize: "0.92619rem",
    fontWeight: "500",
  })),
  DepartedFromDiv: styled("div")(({ theme }) => ({
    color: "rgba(214, 214, 214, 0.6)",
    fontSize: "0.69463rem",
    fontWeight: "500",
    display: "flex",
    justifyContent: "flex-start",
    gap: "0.3rem",
    alignItems: "center",
  })),

  MiddleDiv: styled("div")(({ theme }) => ({
    paddingTop: "1rem",
    paddingBottom: "1rem",
    backgroundColor: "#0D2437",
    width: "100%",
    border: "0.581px solid #0A1313",
    borderTop: "none",
    display: "flex",
    flexDirection: "row",
  })),

  DelayDiv: styled("div")(({ theme }) => ({
    width: "50%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    padding: "0 0.7rem",
    color: "rgba(214, 214, 214, 0.6)",
    fontSize: "0.69463rem",
    fontWeight: "600",
    gap: "0.7rem",
  })),
  GateNumberDiv: styled("div")(({ theme }) => ({
    // width: "50%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "flex-start",
    paddingLeft: "2rem",
    paddingRight: "0.5rem",
    gap: "0.06594rem",
  })),
  TitleDiv: styled("div")(({ theme }) => ({
    color: "rgba(214, 214, 214, 0.6)",
    fontSize: "0.7rem",
    fontWeight: "600",
  })),
  NumberDiv: styled("div")(({ theme }) => ({
    marginRight: "0.5rem",
    color: "#D6D6D6",
    fontSize: "1.2em",
    fontWeight: "700",
  })),

  BottomDiv: styled("div")(({ theme }) => ({
    backgroundColor: "#152E44",
    width: "100%",
    border: "0.581px solid #0A1313",
    borderTop: "none",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    padding: "2rem 0.9rem",
  })),
  Row1: styled("div")(({ theme }) => ({
    paddingBottom: "1rem",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  })),
  Row2: styled("div")(({ theme }) => ({
    paddingTop: "1rem",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  })),
  FlightTimes: styled("div")(({ theme }) => ({
    width: "3rem",
    height: "2.5rem",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "flex-start",
    gap: "0.06rem",
  })),
  TimeTitleDiv: styled("div")(({ theme }) => ({
    color: "rgba(214, 214, 214, 0.6)",
    fontSize: "0.659rem",
    fontWeight: "600",
  })),
  TimeDiv: styled("div")(({ theme }) => ({
    color: "#D6D6D6",
    fontSize: "1.13rem",
    fontWeight: "600",
  })),
  FaddedTimeDiv: styled("div")(({ theme }) => ({
    color: "rgba(214, 214, 214, 0.6)",
    fontSize: "0.85rem",
    fontWeight: "600",
  })),
};

export default DepartedFlightComponentStyles;
