import { IEventConfig } from "../utils/Interfaces";
const flatJson: any[] = [
  {
    id: 1,
    event_id: 1,
    event_name: "Pushback Vechile",
    linked_event_id: null,
    linked_event_name: "",
    event_type: "connect / disconnect",
    min_occurance: 0,
    max_occurance: 1,
    dependency_type: "discconnected",
    start_delay_thresholds: true,
    min_start_delay: 0,
    middle_start_delay: 0,
    max_start_delay: 1,
    ideal_duration: 20,
    min_end_delay: 0,
    middle_end_delay: 0,
    max_end_delay: 1,
    stand_type: [""],
    is_optional: true,
    priority: 1,
    carrier: [
      {
        carrier_name_en: "Saudi Arabia",
        carrier_name_ar: "",
        aircraft_type: "Narrow",
        time_of_day: "Day",
      },
      {
        carrier_name_en: "Emirates",
        carrier_name_ar: "",
        aircraft_type: "Narrow",
        time_of_day: "Night",
      },
      {
        carrier_name_en: "Indigo",
        carrier_name_ar: "",
        aircraft_type: "Narrow",
        time_of_day: "Day",
      },
      {
        carrier_name_en: "Bahrain",
        carrier_name_ar: "",
        aircraft_type: "Narrow",
        time_of_day: "Night",
      },
      {
        carrier_name_en: "Bahrain",
        carrier_name_ar: "",
        aircraft_type: "Wide",
        time_of_day: "Day",
      },
      {
        carrier_name_en: "Bahrain",
        carrier_name_ar: "",
        aircraft_type: "Narrow",
        time_of_day: "Night",
      },
    ],
    children: [],
  },
  {
    id: 2,
    event_id: 2,
    event_name: "Marsheller / VDGS",
    linked_event_id: null,
    linked_event_name: "",
    event_type: "connect / disconnect",
    min_occurance: 1,
    max_occurance: 1,
    dependency_type: "discconnected",
    start_delay_thresholds: true,
    min_start_delay: 0,
    middle_start_delay: 0,
    max_start_delay: 1,
    ideal_duration: 20,
    min_end_delay: 0,
    middle_end_delay: 0,
    max_end_delay: 1,
    stand_type: [""],
    is_optional: false,
    priority: 1,
    carrier: [
      {
        carrier_name_en: "Saudi Arabia",
        carrier_name_ar: "",
        aircraft_type: "Narrow",
        time_of_day: "Day",
      },
      {
        carrier_name_en: "Emirates",
        carrier_name_ar: "",
        aircraft_type: "Wide",
        time_of_day: "Night",
      },
    ],
    children: [],
  },
  {
    id: 3,
    event_id: 3,
    event_name: "Airplane Stationary",
    linked_event_id: 2,
    linked_event_name: "",
    event_type: "connect / disconnect",
    min_occurance: 1,
    max_occurance: 1,
    dependency_type: "discconnected",
    start_delay_thresholds: true,
    min_start_delay: 0,
    middle_start_delay: 0,
    max_start_delay: 1,
    ideal_duration: 20,
    min_end_delay: 0,
    middle_end_delay: 0,
    max_end_delay: 1,
    stand_type: [""],
    is_optional: false,
    priority: 1,
    carrier: [
      {
        carrier_name_en: "Saudi Arabia",
        carrier_name_ar: "",
        aircraft_type: "Narrow",
        time_of_day: "Day",
      },
      {
        carrier_name_en: "Emirates",
        carrier_name_ar: "",
        aircraft_type: "Wide",
        time_of_day: "Night",
      },
    ],
    children: [],
  },
  {
    id: 4,
    event_id: 4,
    event_name: "Chocks On",
    linked_event_id: 3,
    linked_event_name: "",
    event_type: "connect / disconnect",
    min_occurance: 1,
    max_occurance: 1,
    dependency_type: "discconnected",
    start_delay_thresholds: true,
    min_start_delay: 0,
    middle_start_delay: 0,
    max_start_delay: 1,
    ideal_duration: 20,
    min_end_delay: 0,
    middle_end_delay: 0,
    max_end_delay: 1,
    stand_type: [""],
    is_optional: false,
    priority: 1,
    carrier: [
      {
        carrier_name_en: "Saudi Arabia",
        carrier_name_ar: "",
        aircraft_type: "Narrow",
        time_of_day: "Day",
      },
      {
        carrier_name_en: "Indigo",
        carrier_name_ar: "",
        aircraft_type: "Wide",
        time_of_day: "Night",
      },
    ],
    children: [],
  },
  {
    id: 5,
    event_id: 5,
    event_name: "Airplane On-block",
    linked_event_id: 4,
    linked_event_name: "",
    event_type: "connect / disconnect",
    min_occurance: 1,
    max_occurance: 1,
    dependency_type: "discconnected",
    start_delay_thresholds: true,
    min_start_delay: 0,
    middle_start_delay: 0,
    max_start_delay: 1,
    ideal_duration: 20,
    min_end_delay: 0,
    middle_end_delay: 0,
    max_end_delay: 1,
    stand_type: [""],
    is_optional: false,
    priority: 1,
    carrier: [
      {
        carrier_name_en: "Saudi Arabia",
        carrier_name_ar: "",
        aircraft_type: "Narrow",
        time_of_day: "Day",
      },
      {
        carrier_name_en: "Bahrain",
        carrier_name_ar: "",
        aircraft_type: "Wide",
        time_of_day: "Night",
      },
    ],
    children: [],
  },
  {
    id: 6,
    event_id: 6,
    event_name: "Head Set Man",
    linked_event_id: 4,
    linked_event_name: "",
    event_type: "connect / disconnect",
    min_occurance: 1,
    max_occurance: 1,
    dependency_type: "discconnected",
    start_delay_thresholds: true,
    min_start_delay: 0,
    middle_start_delay: 0,
    max_start_delay: 1,
    ideal_duration: 20,
    min_end_delay: 0,
    middle_end_delay: 0,
    max_end_delay: 1,
    stand_type: [""],
    is_optional: false,
    priority: 1,
    carrier: [
      {
        carrier_name_en: "Bahrain",
        carrier_name_ar: "",
        aircraft_type: "Narrow",
        time_of_day: "Day",
      },
      {
        carrier_name_en: "Indigo",
        carrier_name_ar: "",
        aircraft_type: "Wide",
        time_of_day: "Night",
      },
    ],
    children: [],
  },
  {
    id: 7,
    event_id: 7,
    event_name: "Medical Lift",
    linked_event_id: 6,
    linked_event_name: "",
    event_type: "connect / disconnect",
    min_occurance: 1,
    max_occurance: 1,
    dependency_type: "discconnected",
    start_delay_thresholds: true,
    min_start_delay: 0,
    middle_start_delay: 0,
    max_start_delay: 1,
    ideal_duration: 20,
    min_end_delay: 0,
    middle_end_delay: 0,
    max_end_delay: 1,
    stand_type: [""],
    is_optional: false,
    priority: 1,
    carrier: [
      {
        carrier_name_en: "Emirates",
        carrier_name_ar: "",
        aircraft_type: "Narrow",
        time_of_day: "Day",
      },
      {
        carrier_name_en: "Bahrain",
        carrier_name_ar: "",
        aircraft_type: "Wide",
        time_of_day: "Night",
      },
    ],
    children: [],
  },
  {
    id: 8,
    event_id: 8,
    event_name: "Passenger Boarding Bridge",
    linked_event_id: 6,
    linked_event_name: "",
    event_type: "connect / disconnect",
    min_occurance: 1,
    max_occurance: 1,
    dependency_type: "discconnected",
    start_delay_thresholds: true,
    min_start_delay: 0,
    middle_start_delay: 0,
    max_start_delay: 1,
    ideal_duration: 20,
    min_end_delay: 0,
    middle_end_delay: 0,
    max_end_delay: 1,
    stand_type: [""],
    is_optional: false,
    priority: 1,
    carrier: [
      {
        carrier_name_en: "Saudi Arabia",
        carrier_name_ar: "",
        aircraft_type: "Narrow",
        time_of_day: "Day",
      },
      {
        carrier_name_en: "Indigo",
        carrier_name_ar: "",
        aircraft_type: "Wide",
        time_of_day: "Night",
      },
    ],
    children: [],
  },
  {
    id: 9,
    event_id: 9,
    event_name: "Ground Power Unit",
    linked_event_id: 6,
    linked_event_name: "",
    event_type: "connect / disconnect",
    min_occurance: 1,
    max_occurance: 1,
    dependency_type: "discconnected",
    start_delay_thresholds: true,
    min_start_delay: 0,
    middle_start_delay: 0,
    max_start_delay: 1,
    ideal_duration: 20,
    min_end_delay: 0,
    middle_end_delay: 0,
    max_end_delay: 1,
    stand_type: [""],
    is_optional: false,
    priority: 1,
    carrier: [
      {
        carrier_name_en: "Saudi Arabia",
        carrier_name_ar: "",
        aircraft_type: "Narrow",
        time_of_day: "Day",
      },
      {
        carrier_name_en: "Emirates",
        carrier_name_ar: "",
        aircraft_type: "Wide",
        time_of_day: "Night",
      },
    ],
    children: [],
  },
  {
    id: 10,
    event_id: 10,
    event_name: "Pre-Condition Air Events",
    linked_event_id: 6,
    linked_event_name: "",
    event_type: "connect / disconnect",
    min_occurance: 1,
    max_occurance: 1,
    dependency_type: "discconnected",
    start_delay_thresholds: true,
    min_start_delay: 0,
    middle_start_delay: 0,
    max_start_delay: 1,
    ideal_duration: 20,
    min_end_delay: 0,
    middle_end_delay: 0,
    max_end_delay: 1,
    stand_type: [""],
    is_optional: false,
    priority: 1,
    carrier: [
      {
        carrier_name_en: "Bahrain",
        carrier_name_ar: "",
        aircraft_type: "Narrow",
        time_of_day: "Day",
      },
      {
        carrier_name_en: "Indigo",
        carrier_name_ar: "",
        aircraft_type: "Wide",
        time_of_day: "Night",
      },
    ],
    children: [],
  },
  {
    id: 11,
    event_id: 11,
    event_name: "Catering Vehicle",
    linked_event_id: 6,
    linked_event_name: "",
    event_type: "connect / disconnect",
    min_occurance: 1,
    max_occurance: 1,
    dependency_type: "discconnected",
    start_delay_thresholds: true,
    min_start_delay: 0,
    middle_start_delay: 0,
    max_start_delay: 1,
    ideal_duration: 20,
    min_end_delay: 0,
    middle_end_delay: 0,
    max_end_delay: 1,
    stand_type: [""],
    is_optional: false,
    priority: 1,
    carrier: [
      {
        carrier_name_en: "Indigo",
        carrier_name_ar: "",
        aircraft_type: "Narrow",
        time_of_day: "Day",
      },
      {
        carrier_name_en: "Bahrain",
        carrier_name_ar: "",
        aircraft_type: "Wide",
        time_of_day: "Night",
      },
    ],
    children: [],
  },
  {
    id: 12,
    event_id: 12,
    event_name: "Portable Water Truck",
    linked_event_id: 6,
    linked_event_name: "",
    event_type: "connect / disconnect",
    min_occurance: 1,
    max_occurance: 1,
    dependency_type: "discconnected",
    start_delay_thresholds: true,
    min_start_delay: 0,
    middle_start_delay: 0,
    max_start_delay: 1,
    ideal_duration: 20,
    min_end_delay: 0,
    middle_end_delay: 0,
    max_end_delay: 1,
    stand_type: [""],
    is_optional: false,
    priority: 1,
    carrier: [
      {
        carrier_name_en: "Emirates",
        carrier_name_ar: "",
        aircraft_type: "Narrow",
        time_of_day: "Day",
      },
      {
        carrier_name_en: "Indigo",
        carrier_name_ar: "",
        aircraft_type: "Wide",
        time_of_day: "Night",
      },
    ],
    children: [],
  },
  {
    id: 13,
    event_id: 13,
    event_name: "Cargo Loader",
    linked_event_id: 6,
    linked_event_name: "",
    event_type: "connect / disconnect",
    min_occurance: 1,
    max_occurance: 1,
    dependency_type: "discconnected",
    start_delay_thresholds: true,
    min_start_delay: 0,
    middle_start_delay: 0,
    max_start_delay: 1,
    ideal_duration: 20,
    min_end_delay: 0,
    middle_end_delay: 0,
    max_end_delay: 1,
    stand_type: [""],
    is_optional: false,
    priority: 1,
    carrier: [
      {
        carrier_name_en: "Saudi Arabia",
        carrier_name_ar: "",
        aircraft_type: "Narrow",
        time_of_day: "Day",
      },
      {
        carrier_name_en: "Bahrain",
        carrier_name_ar: "",
        aircraft_type: "Wide",
        time_of_day: "Night",
      },
    ],
    children: [],
  },
  {
    id: 14,
    event_id: 14,
    event_name: "Belt Loader",
    linked_event_id: 13,
    linked_event_name: "",
    event_type: "connect / disconnect",
    min_occurance: 1,
    max_occurance: 1,
    dependency_type: "discconnected",
    start_delay_thresholds: true,
    min_start_delay: 0,
    middle_start_delay: 0,
    max_start_delay: 1,
    ideal_duration: 20,
    min_end_delay: 0,
    middle_end_delay: 0,
    max_end_delay: 1,
    stand_type: [""],
    is_optional: false,
    priority: 1,
    carrier: [
      {
        carrier_name_en: "Bahrain",
        carrier_name_ar: "",
        aircraft_type: "Narrow",
        time_of_day: "Day",
      },
      {
        carrier_name_en: "Indigo",
        carrier_name_ar: "",
        aircraft_type: "Wide",
        time_of_day: "Night",
      },
    ],
    children: [],
  },
  {
    id: 15,
    event_id: 15,
    event_name: "Unloading",
    linked_event_id: 14,
    linked_event_name: "",
    event_type: "connect / disconnect",
    min_occurance: 1,
    max_occurance: 1,
    dependency_type: "discconnected",
    start_delay_thresholds: true,
    min_start_delay: 0,
    middle_start_delay: 0,
    max_start_delay: 1,
    ideal_duration: 20,
    min_end_delay: 0,
    middle_end_delay: 0,
    max_end_delay: 1,
    stand_type: [""],
    is_optional: false,
    priority: 1,
    carrier: [
      {
        carrier_name_en: "Indigo",
        carrier_name_ar: "",
        aircraft_type: "Narrow",
        time_of_day: "Day",
      },
      {
        carrier_name_en: "Emirates",
        carrier_name_ar: "",
        aircraft_type: "Wide",
        time_of_day: "Night",
      },
    ],
    children: [],
  },
  {
    id: 16,
    event_id: 16,
    event_name: "Loading",
    linked_event_id: 15,
    linked_event_name: "",
    event_type: "connect / disconnect",
    min_occurance: 1,
    max_occurance: 1,
    dependency_type: "discconnected",
    start_delay_thresholds: true,
    min_start_delay: 0,
    middle_start_delay: 0,
    max_start_delay: 1,
    ideal_duration: 20,
    min_end_delay: 0,
    middle_end_delay: 0,
    max_end_delay: 1,
    stand_type: [""],
    is_optional: false,
    priority: 1,
    carrier: [
      {
        carrier_name_en: "Saudi Arabia",
        carrier_name_ar: "",
        aircraft_type: "Narrow",
        time_of_day: "Day",
      },
      {
        carrier_name_en: "Indigo",
        carrier_name_ar: "",
        aircraft_type: "Wide",
        time_of_day: "Night",
      },
    ],
    children: [],
  },
  {
    id: 17,
    event_id: 17,
    event_name: "Dolly",
    linked_event_id: 13,
    linked_event_name: "",
    event_type: "connect / disconnect",
    min_occurance: 1,
    max_occurance: 1,
    dependency_type: "discconnected",
    start_delay_thresholds: true,
    min_start_delay: 0,
    middle_start_delay: 0,
    max_start_delay: 1,
    ideal_duration: 20,
    min_end_delay: 0,
    middle_end_delay: 0,
    max_end_delay: 1,
    stand_type: [""],
    is_optional: false,
    priority: 1,
    carrier: [
      {
        carrier_name_en: "Saudi Arabia",
        carrier_name_ar: "",
        aircraft_type: "Narrow",
        time_of_day: "Day",
      },
      {
        carrier_name_en: "Emirates",
        carrier_name_ar: "",
        aircraft_type: "Wide",
        time_of_day: "Night",
      },
    ],
    children: [],
  },
  {
    id: 18,
    event_id: 18,
    event_name: "Fuelling Truck",
    linked_event_id: 6,
    linked_event_name: "",
    event_type: "connect / disconnect",
    min_occurance: 1,
    max_occurance: 1,
    dependency_type: "discconnected",
    start_delay_thresholds: true,
    min_start_delay: 0,
    middle_start_delay: 0,
    max_start_delay: 1,
    ideal_duration: 20,
    min_end_delay: 0,
    middle_end_delay: 0,
    max_end_delay: 1,
    stand_type: [""],
    is_optional: false,
    priority: 1,
    carrier: [
      {
        carrier_name_en: "Emirates",
        carrier_name_ar: "",
        aircraft_type: "Narrow",
        time_of_day: "Day",
      },
      {
        carrier_name_en: "Indigo",
        carrier_name_ar: "",
        aircraft_type: "Wide",
        time_of_day: "Night",
      },
    ],
    children: [],
  },
  {
    id: 19,
    event_id: 19,
    event_name: "Chocks Off",
    linked_event_id: 18,
    linked_event_name: "",
    event_type: "connect / disconnect",
    min_occurance: 1,
    max_occurance: 1,
    dependency_type: "discconnected",
    start_delay_thresholds: true,
    min_start_delay: 0,
    middle_start_delay: 0,
    max_start_delay: 1,
    ideal_duration: 20,
    min_end_delay: 0,
    middle_end_delay: 0,
    max_end_delay: 1,
    stand_type: [""],
    is_optional: false,
    priority: 1,
    carrier: [
      {
        carrier_name_en: "Bahrain",
        carrier_name_ar: "",
        aircraft_type: "Narrow",
        time_of_day: "Day",
      },
      {
        carrier_name_en: "Emirates",
        carrier_name_ar: "",
        aircraft_type: "Wide",
        time_of_day: "Night",
      },
    ],
    children: [],
  },
  {
    id: 20,
    event_id: 20,
    event_name: "Pushback Vechile",
    linked_event_id: 19,
    linked_event_name: "",
    event_type: "connect / disconnect",
    min_occurance: 1,
    max_occurance: 1,
    dependency_type: "discconnected",
    start_delay_thresholds: true,
    min_start_delay: 0,
    middle_start_delay: 0,
    max_start_delay: 1,
    ideal_duration: 20,
    min_end_delay: 0,
    middle_end_delay: 0,
    max_end_delay: 1,
    stand_type: [""],
    is_optional: false,
    priority: 1,
    carrier: [
      {
        carrier_name_en: "Saudi Arabia",
        carrier_name_ar: "",
        aircraft_type: "Narrow",
        time_of_day: "Day",
      },
      {
        carrier_name_en: "Emirates",
        carrier_name_ar: "",
        aircraft_type: "Wide",
        time_of_day: "Night",
      },
    ],
    children: [],
  },
  {
    id: 21,
    event_id: 21,
    event_name: "Airplane Off-Block",
    linked_event_id: 20,
    linked_event_name: "",
    event_type: "connect / disconnect",
    min_occurance: 1,
    max_occurance: 1,
    dependency_type: "discconnected",
    start_delay_thresholds: true,
    min_start_delay: 0,
    middle_start_delay: 0,
    max_start_delay: 1,
    ideal_duration: 20,
    min_end_delay: 0,
    middle_end_delay: 0,
    max_end_delay: 1,
    stand_type: [""],
    is_optional: false,
    priority: 1,
    carrier: [
      {
        carrier_name_en: "Saudi Arabia",
        carrier_name_ar: "",
        aircraft_type: "Narrow",
        time_of_day: "Day",
      },
      {
        carrier_name_en: "Emirates",
        carrier_name_ar: "",
        aircraft_type: "Wide",
        time_of_day: "Night",
      },
    ],
    children: [],
  },
];
export default flatJson;
