import { IEvent } from "../utils/Interfaces";
const flatJson2: any[] = [
  {
    eventId: 1,
    eventName: "Pushback Vechile",
    isOptional: true,
    occurance: 1,
    linkedTo: null,
    priority: 1,
    children: [],
  },
  {
    eventId: 2,
    eventName: "Marsheller / VDGS",
    isOptional: false,
    occurance: 1,
    linkedTo: null,
    priority: 1,
    children: [],
  },
  {
    eventId: 3,
    eventName: "Airplane Stationary",
    isOptional: false,
    occurance: 1,
    linkedTo: 2,
    priority: null,
    children: [],
  },
  {
    eventId: 4,
    eventName: "Chocks On",
    isOptional: false,
    occurance: 1,
    linkedTo: 3,
    priority: null,
    children: [],
  },
  {
    eventId: 5,
    eventName: "Airplane On-block",
    isOptional: false,
    occurance: 1,
    linkedTo: 4,
    priority: 1,
    children: [],
  },
  {
    eventId: 6,
    eventName: "Head Set Man",
    isOptional: false,
    occurance: 1,
    linkedTo: 4,
    priority: 1,
    children: [],
  },
  {
    eventId: 7,
    eventName: "Medical Lift",
    isOptional: false,
    occurance: 1,
    linkedTo: 6,
    priority: 1,
    children: [],
  },
  {
    eventId: 8,
    eventName: "Passenger Boarding Bridge",
    isOptional: false,
    occurance: 1,
    linkedTo: 6,
    priority: 1,
    children: [],
  },
  {
    eventId: 9,
    eventName: "Ground Power Unit",
    isOptional: false,
    occurance: 1,
    linkedTo: 6,
    priority: null,
    children: [],
  },
  {
    eventId: 10,
    eventName: "Pre-Condition Air Events",
    isOptional: false,
    occurance: 1,
    linkedTo: 6,
    priority: 1,
    children: [],
  },
  {
    eventId: 11,
    eventName: "Catering Vehicle",
    isOptional: false,
    occurance: 1,
    linkedTo: 6,
    priority: 1,
    children: [],
  },
  {
    eventId: 12,
    eventName: "Portable Water Truck",
    isOptional: false,
    occurance: 1,
    linkedTo: 6,
    priority: 1,
    children: [],
  },
  {
    eventId: 13,
    eventName: "Cargo Loader",
    isOptional: false,
    occurance: 1,
    linkedTo: 6,
    priority: 1,
    children: [],
  },
  {
    eventId: 14,
    eventName: "Belt Loader",
    isOptional: false,
    occurance: 1,
    linkedTo: 13,
    priority: 1,
    children: [],
  },
  {
    eventId: 15,
    eventName: "Unloading",
    isOptional: false,
    occurance: 1,
    linkedTo: 14,
    priority: null,
    children: [],
  },
  {
    eventId: 16,
    eventName: "Loading",
    isOptional: false,
    occurance: 1,
    linkedTo: 15,
    priority: null,
    children: [],
  },
  {
    eventId: 17,
    eventName: "Dolly",
    isOptional: false,
    occurance: 1,
    linkedTo: 13,
    priority: 2,
    children: [],
  },
  {
    eventId: 18,
    eventName: "Fuelling Truck",
    isOptional: false,
    occurance: 1,
    linkedTo: 6,
    priority: 2,
    children: [],
  },
  {
    eventId: 19,
    eventName: "Chocks Off",
    isOptional: false,
    occurance: 1,
    linkedTo: 18,
    priority: null,
    children: [],
  },
  {
    eventId: 20,
    eventName: "Pushback Vechile",
    isOptional: false,
    occurance: 1,
    linkedTo: 19,
    priority: null,
    children: [],
  },
  {
    eventId: 21,
    eventName: "Airplane Off-Block",
    isOptional: false,
    occurance: 1,
    linkedTo: 20,
    priority: null,
    children: [],
  },
];
export default flatJson2;
